import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, XCircle } from 'lucide-react';
import type { HistoryEntry } from '@/types';
import { mockHistory } from '@/data/mockData';

interface HistoryPageProps { onViewAnalysis: (id: string) => void; onNewAnalysis: () => void; }

const statusConfig = { Completed: { icon: CheckCircle2, className: 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20' }, Processing: { icon: Clock3, className: 'text-cyan-400 bg-cyan-400/10 border-cyan-400/20' }, Failed: { icon: XCircle, className: 'text-red-400 bg-red-400/10 border-red-400/20' } };

function HistoryStatus({ status }: { status: HistoryEntry['status'] }) { const config = statusConfig[status]; const Icon = config.icon; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${config.className}`}><Icon className="h-3.5 w-3.5" />{status}</span>; }

export default function HistoryPage({ onViewAnalysis, onNewAnalysis }: HistoryPageProps) {
  return <div className="min-h-screen pt-28 pb-20"><main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-10"><div><div className="section-label mb-4">Your workspace</div><h1 className="font-display text-4xl sm:text-5xl font-semibold tracking-tight text-white">Analysis history</h1><p className="mt-4 text-lg text-slate-400">Review decisions you’ve put through the Veritas lens.</p></div><button onClick={onNewAnalysis} className="btn-primary shrink-0"><span className="text-lg leading-none">+</span> New analysis</button></div><div className="glass-card overflow-hidden"><div className="hidden lg:grid grid-cols-[minmax(0,1fr)_120px_140px_150px_130px] gap-4 px-6 py-4 border-b border-white/[0.05] text-xs font-semibold uppercase tracking-widest text-slate-600"><span>Decision</span><span>Date</span><span>Assumptions</span><span>Financial warnings</span><span>Status</span></div><div className="divide-y divide-white/[0.04]">{mockHistory.map((entry) => <div key={entry.id} className="grid lg:grid-cols-[minmax(0,1fr)_120px_140px_150px_130px] gap-4 items-center px-6 py-5 hover:bg-white/[0.02] transition-colors"><div className="min-w-0"><div className="flex items-center gap-2 mb-1"><span className="font-mono text-[10px] text-slate-600">{entry.id}</span></div><p className="text-sm font-medium leading-relaxed text-slate-200 truncate">{entry.decision}</p><div className="flex lg:hidden items-center gap-4 mt-3"><span className="text-xs text-slate-500">{entry.date}</span><span className="text-xs text-slate-500">{entry.assumptionCount} assumptions</span>{entry.financialWarnings > 0 && <span className="inline-flex items-center gap-1 text-xs text-amber-400"><AlertTriangle className="h-3 w-3" /> {entry.financialWarnings} warning{entry.financialWarnings > 1 ? 's' : ''}</span>}</div></div><span className="hidden lg:block text-sm text-slate-500">{entry.date}</span><span className="hidden lg:block text-sm text-slate-400">{entry.assumptionCount} <span className="text-slate-600">found</span></span><span className="hidden lg:inline-flex items-center gap-1.5 text-sm text-slate-400">{entry.financialWarnings > 0 ? <><AlertTriangle className="h-3.5 w-3.5 text-amber-400" /> {entry.financialWarnings} warning{entry.financialWarnings > 1 ? 's' : ''}</> : <span className="text-slate-600">None</span>}</span><div className="flex items-center justify-between lg:justify-start gap-4"><HistoryStatus status={entry.status} />{entry.status === 'Completed' && <button onClick={() => onViewAnalysis(entry.id)} className="inline-flex items-center gap-1 text-xs font-medium text-cyan-400 hover:text-cyan-300 transition-colors">View <ArrowRight className="h-3.5 w-3.5" /></button>}</div></div>)}</div></div><p className="mt-5 text-center text-xs text-slate-600">Showing {mockHistory.length} analyses · Decisions are stored securely in your workspace</p></main></div>;
}
